---
# tasks file for pe_role

- name: install packages
  package:
    name:
      - nginx
      - firewalld
    state: present

- name: check if directory exists
  command: "ls {{ doc_root }}"
  register: directory_exists
  ignore_errors: true

- name: create directory
  ansible.builtin.file:
    path: "{{ doc_root }}"
    state: directory
  when: directory_exists is failed

- name: check if index.html exists
  command: "cat {{ doc_root }}/index.html"
  register: index_exists
  ignore_errors: true

- name: copy the template to the host
  template:
    src: templates/landing-page.html.j2
    dest: "{{ doc_root }}/index.html"
  when: index_exists is failed

- name: setup server configuration in nginx
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/mypage.conf

- name: change /var/www/ to /var/www/mypage
  lineinfile:
        path: /etc/nginx/conf.d/mypage.conf
        regexp: '/var/www/$'
        line: "root {{ doc_root }};"
  notify: restart nginx

- name: ensure port 8080 is open 
  firewalld:
    port: "{{ web_port }}/tcp"
    permanent: true
    state: enabled
  notify: restart firewalld
