apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-script
  namespace: default
data:
  CreateDB.sql: |-
    CREATE TABLE text (
        id serial PRIMARY KEY,
        text VARCHAR ( 100 ) UNIQUE NOT NULL
    );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: default
data:
  database-uri: postgresql
  database-user: myname
  postgres-db: postgres
