apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: driesmelottepxl/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: database-uri
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 5000
  selector:
    app: backend
